/**
 * Regenerates the typed API client from the Rust API's OpenAPI document.
 *
 * The spec comes from `cargo run -- --dump-openapi`, which builds the document
 * from the same router the server mounts, without needing a database or a
 * running API. Both outputs are written only after every step succeeds, so a
 * compile error in the API leaves the previous, working client in place.
 *
 * Run with: pnpm generate:api
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const apiManifest = join(webRoot, "..", "api", "Cargo.toml");
const specPath = join(webRoot, "lib", "api", "openapi.json");
const typesPath = join(webRoot, "lib", "api", "schema.d.ts");

const cargo = spawnSync(
  "cargo",
  ["run", "--quiet", "--manifest-path", apiManifest, "--", "--dump-openapi"],
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
);

if (cargo.error?.code === "ENOENT") {
  console.error(
    "cargo not found on PATH. Install Rust (https://rustup.rs) or run this from a shell where cargo is available.",
  );
  process.exit(1);
}

if (cargo.status !== 0) {
  console.error(cargo.stderr?.trim() || "cargo run -- --dump-openapi failed");
  process.exit(cargo.status ?? 1);
}

let spec;
try {
  spec = JSON.parse(cargo.stdout);
} catch (cause) {
  console.error("--dump-openapi did not produce valid JSON:", cause.message);
  process.exit(1);
}

// `openapiTS` mutates nothing, but it does resolve $refs against the object it
// is given, so the parsed spec is handed over directly rather than re-read.
const types = astToString(await openapiTS(spec));

mkdirSync(dirname(specPath), { recursive: true });
writeFileSync(specPath, `${JSON.stringify(spec, null, 2)}\n`);
writeFileSync(
  typesPath,
  `/**\n * Generated by \`pnpm generate:api\` from the Rust API's OpenAPI document.\n * Do not edit by hand; change the API and regenerate.\n */\n\n${types}`,
);

const pathCount = Object.keys(spec.paths ?? {}).length;
const schemaCount = Object.keys(spec.components?.schemas ?? {}).length;
console.log(
  `Generated lib/api/schema.d.ts — ${pathCount} paths, ${schemaCount} schemas (API v${spec.info?.version}).`,
);
