/**
 * Typed client for the Rust API.
 *
 * `schema.d.ts` and `openapi.json` are generated by `pnpm generate:api` from
 * the API's own OpenAPI document — never edit them by hand. Rerun that script
 * after any change to a route or a `ToSchema` type.
 */
export { api, bearer, createApiClient } from "./client";
export type { components, operations, paths } from "./schema";

import type { components } from "./schema";

type Schemas = components["schemas"];

export type ErrorResponse = Schemas["ErrorResponse"];
export type ForgotPasswordRequest = Schemas["ForgotPasswordRequest"];
export type LoginRequest = Schemas["LoginRequest"];
export type MessageResponse = Schemas["MessageResponse"];
export type RefreshRequest = Schemas["RefreshRequest"];
export type RegisterRequest = Schemas["RegisterRequest"];
export type ResetPasswordRequest = Schemas["ResetPasswordRequest"];
export type Session = Schemas["Session"];
export type TokenPair = Schemas["TokenPair"];
export type User = Schemas["User"];
export type VerifyTokenRequest = Schemas["VerifyTokenRequest"];
export type VerifyTokenResponse = Schemas["VerifyTokenResponse"];
