const API_URL = (process.env.API_URL ?? "http://localhost:8080").replace(
  /\/+$/,
  "",
);

/**
 * Serves the OpenAPI document generated by the Rust API from this origin.
 *
 * Proxying it means the docs page never needs a cross-origin request just to
 * load the spec, so a CORS misconfiguration shows up as a failing request
 * against the API rather than a blank page.
 */
export async function GET() {
  let upstream: Response;

  try {
    upstream = await fetch(`${API_URL}/openapi.json`, { cache: "no-store" });
  } catch {
    return Response.json(
      { error: "api_unreachable", message: `Could not reach ${API_URL}` },
      { status: 502 },
    );
  }

  if (!upstream.ok) {
    return Response.json(
      {
        error: "api_error",
        message: `${API_URL}/openapi.json responded with ${upstream.status}`,
      },
      { status: 502 },
    );
  }

  return new Response(await upstream.text(), {
    headers: {
      "content-type": "application/json",
      "cache-control": "no-store",
    },
  });
}
